spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${var.database.name}
    username: postgres
    password: ${DB_PWD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
